### PR TITLE
Force database parameter must be omitted or have the same value as schema 

### LINKED ISSUE #93: Force database parameter must be omitted or have the same value as schema
### Describe the feature
Force database parameter must be omitted or have the same value as schema

### Describe alternatives you've considered
Modify credentials to use the same that dbt-spark is using

### Who will this benefit?
Everyone that is using the adapter. 

### Are you interested in contributing this feature?
yes

### PR DESCRIPTION
**Pull request by armaseg**
resolves #93 

### Description

Changes in credentials

### Checklist

- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-glue next" section.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nicor88** [comment]
@armaseg when testing this PR (I removed my database from my profile). I'm getting this error:
>  Credentials in profile "glue", target "dev" invalid: 'database' is a required property

I see bunch of places where the database is used:
* sample profile: https://github.com/aws-samples/dbt-glue/blob/main/dbt/include/glue/sample_profiles.yml#L21
* this macro: https://github.com/aws-samples/dbt-glue/blob/3c86a8a4f7c5dc200beaef42493534c85fe9ecc2/dbt/include/glue/macros/adapters.sql#L92, should be rather target.schema
* seeds: https://github.com/aws-samples/dbt-glue/blob/1b50527ca9cd1c5bae919ac1f39a3166930b6846/dbt/include/glue/macros/materializations/seed.sql#L10-L11

If I understood correctly with this feature we should be able to don't pass the `database` in the profile, am I right?

**Comment by armaseg** [comment]
Totally missed it! Thank you @nicor88 :)

**Review by nicor88 — APPROVED** [review]
@armaseg I tested your latest changes, it works well (again I omitted database from my profile). Thanks for your changes. For me this is ready to be 🚢

**Comment by nicor88** [comment]
@armaseg So I tested the following:
* a simple dbt run on a model ✅ 
* dbt seed with a sample csv (I did run it multiple times just to be sure) ✅ 

so far all works well.

**Pull request merged**
